### ISSUE TITLE
[4pt]  Fetch rockets - Fetch data

### ISSUE THREAD

**Issue by andgarzonmal** [David-Verde/Pair-Space-Travelers-Hub#17]
Fetch data from the Rockets endpoint  (https://api.spacexdata.com/v3/rockets) when the application starts (as Rockets is the default view).

Once the data are fetched, dispatch an action to store the selected data in Redux store:

- id
- name
- type
- flickr_images

NOTE: Make sure you only dispatch those actions once and do not add data to store on every re-render (i.e. when changing views / using navigation).

**Comment by David-Verde** [comment]
![image](https://user-images.githubusercontent.com/99683363/179853529-9201a748-f63e-4ef5-a8b9-3e6413cbafa1.png)
Fetch data from Rockets API
