### ISSUE TITLE
[1pt] Create basic structure for Missions - Setup

### ISSUE THREAD

**Issue by andgarzonmal** [David-Verde/Pair-Space-Travelers-Hub#20]
- Create a route and a view component. Use `<NavLink />` for the page navigation links and style active class to indicate which section/page the user is currently on (underline active navigation link).
- Create a directory for all Redux state slice files.

**Comment by David-Verde** [comment]
![image](https://user-images.githubusercontent.com/99683363/179852998-46852115-a62c-428d-8e09-aab204d7b44f.png)
Finished create the basics for missions module.
