### ISSUE TITLE
[1pt] Create basic structure for Rockets - Setup

### ISSUE THREAD

**Issue by andgarzonmal** [David-Verde/Pair-Space-Travelers-Hub#21]
- Create a route and a view component. Use `<NavLink />` for the page navigation links and style active class to indicate which section/page the user is currently on (underline active navigation link).
- Create a directory for all Redux state slice files.

**Comment by David-Verde** [comment]
![image](https://user-images.githubusercontent.com/99683363/179853480-f44bbd61-53ff-4d8a-a8f9-cdbbf074de78.png)
Created basic structure for rockets module
