### ISSUE TITLE
[1pt] Create empty My profile - Setup (group task)

### ISSUE THREAD

**Issue by andgarzonmal** [David-Verde/Pair-Space-Travelers-Hub#22]
- Create a route and a view component. Use `<NavLink />` for the page navigation links and style active class to indicate which section/page the user is currently on (underline active navigation link).
- This view should be empty - you will add content in separate tasks.

**Comment by David-Verde** [comment]
![image](https://user-images.githubusercontent.com/99683363/179852801-ade9a9aa-96b6-4a1a-8eae-b9d37ba97a9c.png)
We finish create the empty profile module
