### ISSUE TITLE
[1pt] Create website header with empty nav - Setup (group task)

### ISSUE THREAD

**Issue by andgarzonmal** [David-Verde/Pair-Space-Travelers-Hub#23]
- Download the [free image](https://www.flaticon.com/free-icon/planet_3212567?term=space&page=1&position=19&page=1&position=19&related_id=3212567&origin=style) for the app logo.
- Create **empty** navigation (this will be filled in in separate tasks).

**Comment by David-Verde** [comment]
![image](https://user-images.githubusercontent.com/99683363/179852652-255d658c-6bbb-43cd-9138-66d62fc50bd3.png)
Already created the navbar.
